
-- 1. Create the SurveyAxes table to store structural parameters
CREATE TABLE survey_axes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    title TEXT NOT NULL,
    description TEXT,
    "order" INT NOT NULL DEFAULT 0,
    is_active BOOLEAN DEFAULT TRUE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Add comments for clarity
COMMENT ON TABLE survey_axes IS 'Справочник структурных параметров (осей) пространства опросов.';
COMMENT ON COLUMN survey_axes.code IS 'Уникальный текстовый код параметра (например, survey_goal).';
COMMENT ON COLUMN survey_axes.title IS 'Человекочитаемое название параметра (например, Цель опроса).';
COMMENT ON COLUMN survey_axes.description IS 'Подробное описание сути параметра.';
COMMENT ON COLUMN survey_axes."order" IS 'Порядок сортировки для отображения.';


-- 2. Create the SurveyAxisValues table to store parameter values
CREATE TABLE survey_axis_values (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    axis_id BIGINT NOT NULL REFERENCES survey_axes(id) ON DELETE CASCADE,
    value_code TEXT NOT NULL,
    label TEXT NOT NULL,
    description TEXT,
    "order" INT NOT NULL DEFAULT 0,
    is_active BOOLEAN DEFAULT TRUE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Add a unique constraint for value_code within each axis
ALTER TABLE survey_axis_values ADD CONSTRAINT survey_axis_values_axis_id_value_code_key UNIQUE (axis_id, value_code);

-- Add comments for clarity
COMMENT ON TABLE survey_axis_values IS 'Справочник возможных значений для каждого структурного параметра (оси).';
COMMENT ON COLUMN survey_axis_values.axis_id IS 'Ссылка на родительский параметр (ось).';
COMMENT ON COLUMN survey_axis_values.value_code IS 'Уникальный (в рамках оси) код значения (например, research).';
COMMENT ON COLUMN survey_axis_values.label IS 'Человекочитаемое название значения (например, Исследование).';
COMMENT ON COLUMN survey_axis_values.description IS 'Подробное описание сути значения.';
COMMENT ON COLUMN survey_axis_values."order" IS 'Порядок сортировки для отображения.';

