/*
  # Add AI Survey Features

  1. Changes to `survey_templates` table
    - Add `is_ai_generated` (boolean) - indicates if survey was generated by AI
    - Add `is_interactive` (boolean) - indicates if survey uses interactive chat mode
    - Add `ai_generation_topic` (text) - stores the original topic used for AI generation
    
  2. Notes
    - Both fields default to false for backward compatibility
    - Interactive surveys use chat-based Q&A flow
    - AI-generated surveys can be either interactive or traditional
*/

DO $$
BEGIN
  -- Add is_ai_generated column
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'survey_templates' AND column_name = 'is_ai_generated'
  ) THEN
    ALTER TABLE survey_templates ADD COLUMN is_ai_generated boolean DEFAULT false;
  END IF;

  -- Add is_interactive column
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'survey_templates' AND column_name = 'is_interactive'
  ) THEN
    ALTER TABLE survey_templates ADD COLUMN is_interactive boolean DEFAULT false;
  END IF;

  -- Add ai_generation_topic column
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'survey_templates' AND column_name = 'ai_generation_topic'
  ) THEN
    ALTER TABLE survey_templates ADD COLUMN ai_generation_topic text;
  END IF;
END $$;